# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2017
  project: extra salt
  version: 0.1
  release: 0.1.7
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    saltedpasswords:
    - http://docs.typo3.org/typo3cms/extensions/saltedpasswords/
    - null
    external_import:
    - https://docs.typo3.org/typo3cms/extensions/external_import/
    - null
  latex_documents:
  - - Index
    - extrasalt.tex
    - extra salt
    - Christoph Holtermann 
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage
  html_theme_options:
    github_repository: c-holtermann/extrasalt
    github_branch: latest
...
